### ISSUE TITLE
Accelerad 0.7 beta can't open open test.vf file

### ISSUE THREAD

**Issue by ymg2007** [nljones/Accelerad#1]
I just install Accelerad 0.7 beta version. After the test， accelerad_rcontrib\accelerad_rpict\accelerad_rtrace succeeded! I am so exited for it . But test_AcceleradRT failed. It gived me an error  showed blow.
![20190428180211](https://user-images.githubusercontent.com/24608776/56862686-23756e00-69e0-11e9-91a0-e3f55b4a436f.png)
I am using Radiance 5.2 and Windows 10 home edition. 
Please help debug it.

**Comment by nljones** [comment]
Can you verify that the file _test.vf_ exists in the same directory as _test_AcceleradRT.bat_?

The file _test.vf_ should be a text file with the following contents:
`rvu -vp 10.0 -2.0 1.5 -vd -1.0 0.0 0.0 -vu 0 0 1 -vta -vh 180 -vv 180`

You can also add the view arguments directly to the batch file as follows:
`AcceleradRT -vp 10.0 -2.0 1.5 -vd -1.0 0.0 0.0 -vu 0 0 1 -vta -vh 180 -vv 180 -ab 3 -aa 0 -ad 1 -x 768 -y 768 -s 10000 -log 3 test.oct`

**Comment by ymg2007** [comment]
Hi,nljones. Thanks for your reply.I re-installed Accelerad 0.7 beta.Now it worked perfectly.
![D5R5yF_U8AA6vGo](https://user-images.githubusercontent.com/24608776/56872912-d84f6f80-6a60-11e9-89b9-0136d968eabd.jpg)
![D5R50AlU8AAfGKN](https://user-images.githubusercontent.com/24608776/56872916-dd142380-6a60-11e9-80c2-97f3f4f3f1a2.jpg)
