### ISSUE TITLE
Installation process of Accelerad on Linux.

### ISSUE THREAD

**Issue by abnersss** [nljones/Accelerad#10]
Hi Nathaniel,

Recently, I started to try the Accelerad. I already finished the three steps from the "Before you begin":  having a CUDA-enabled GPU, installing Radiance, and installing graphics driver.  Then I downloaded and unpacked the accelerad_07_beta_linux.tar.gz, and added the Accelerad bin folder to the PATH and LD_LIBRARY_PATH environment variables. Is the installation finished?

Warm regard,

Hao

**Comment by nljones** [comment]
This is not a code issue, so please see the discussion on the [Radiance Discourse](https://discourse.radiance-online.org/t/how-to-install-accelerad-on-linux/6586).
