### ISSUE TITLE
calculation of contribution from artificial light with accelerad_rcontrib

### ISSUE THREAD

**Issue by XiaomingY** [nljones/Accelerad#2]
Hi Nathaniel,

Thank you for the amazing tool! I tried to calculate contribution from each artificial light source. Is this possible with accelerad_rcontrib? I tried the following commands with the attached file. 

```
oconv material.rad GenericFurniture_50_0.rad artificialLight.rad  > artificial.oct                                                        

accelerad_rpict -vf view.vf -ab 2 artificial.oct> artificial_rpict.hdr                                                                    

vwrays -vf view.vf -x 500 -y 500 -ff | accelerad_rcontrib -V+ -ffc -x 500 -y 308 -ld- -fo -ab 2 -o contribution_accelerad.hdr -m DefaultLightGroup_BD30_1626_1_light artificial.oct

vwrays -vf view.vf -x 500 -y 500 -ff | rcontrib -V+ -ffc -x 500 -y 308 -ld- -fo -ab 2 -o contribution_rcontrib.hdr -m DefaultLightGroup_BD30_1626_1_light artificial.oct
```
[models.zip](https://github.com/nljones/Accelerad/files/3467101/models.zip)

The render of artificial light works well with accelerad_rpict, but accelerad_rcontrib gives black image. Rcontrib gives image as expected. Is this because of a feature not supported by accelerad_rcontrib yet? Thank you for your help.

**Comment by nljones** [comment]
This has been corrected in commit c64ee7eeaae4ae82564c687c994a2d1c006afa5a.
