### ISSUE TITLE
accelerad_rpict renders strange all black pixels in image

### ISSUE THREAD

**Issue by maqorbani** [nljones/Accelerad#5]
Hey everyone! I hope you are all well.

First I wanted to thank you sincerely for this notable and great project of Accelerad!

It's been a time that I have been working with Accelerad and mostly using your Accelerad_RT and I had no issues with Accelerad_RT, but my problem is with Accelerad_rpict where I can render images just as the Radiance_rpict although images rendered with Accelerad_rpict, have some strange looking

**Comment by nljones** [comment]
Closing this issue, as it is a [duplicate](https://groups.google.com/g/accelerad-users/c/3NdYC3KSX18).
