### ISSUE TITLE
accelerad_rpict renders strange all black pixels in image

### ISSUE THREAD

**Issue by maqorbani** [nljones/Accelerad#6]
Hey everyone! I hope you are all well.

First I wanted to thank you sincerely for this notable and great project of Accelerad!

It's been a time that I have been working with Accelerad and mostly using your Accelerad_RT and I had no issues with Accelerad_RT, but my problem is with Accelerad_rpict where I can render images just as the Radiance_rpict although images rendered with Accelerad_rpict, have some strange looks, where in some parts of the image there would be some pixels all rendered completely black and among them there are some cluster of pixels that form a circle that look to have been correctly rendered. 
Below I have uploaded images of the accelerad demo room, first one with -ab 4 and second one with -ab 8 and the third image is a screenshot of a room I designed being previewed on Accelerad_RT.
I am using the latest windows 10 update, and my graphics card is a RTX 2070 max-q design.
I have CUDA version 10.1 and optix version 7.0.0 installed.

I was hopping if you could help solve this issue. Thank you in advance.

![AB4](https://user-images.githubusercontent.com/47574645/106899979-39fb3e00-670b-11eb-9dff-c6f1c365b5f8.png)

![AB8](https://user-images.githubusercontent.com/47574645/106899405-901bb180-670a-11eb-997a-0162b023afa5.png)

![image](https://user-images.githubusercontent.com/47574645/106903028-bcd1c800-670e-11eb-973b-62480c313abc.png)

Best regards.

**Comment by maqorbani** [comment]
And here's an image of the default settings of the Accelerad demo file without any settings changed.

![image](https://user-images.githubusercontent.com/47574645/106901543-281a9a80-670d-11eb-99d7-ef1858c82f1f.png)

**Comment by nljones** [comment]
Closing this issue, as it is a [duplicate](https://groups.google.com/g/accelerad-users/c/3NdYC3KSX18).

**Comment by maqorbani** [comment]
I am really sorry I was going to delete this issue after I found out about the google group and after I posted the same issue there.

Best regards.
