### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by kusozayka** [nljones/Accelerad#7]
For one of our researchers we're trying to compile this software on one of our computing nodes with failing results. I hope you can assist us with the problem;

We're using the latest changes of the `combined` branch. We're compiling this on a CentOS 7.9 machine with the latest OptiX SDK (7.6.0). Please let me know if you need any more information.

(previous steps like `cmake` are not shown)
> [20194262@arch-gpuA001 Accelerad]$ make
[ 13%] Built target rtrad
[ 14%] Built target rgl
[ 14%] Built target mgf
[ 14%] Built target wfobj
[ 15%] Built target libreetz
[ 24%] Built target radiance
[ 24%] Built target testBSDF
[ 25%] Built target ev
[ 25%] Built target histo
[ 25%] Linking C executable ../../bin/icalc
../common/librtrad.a(getpath.c.o): In function `getpath':
getpath.c:(.text+0x5d): undefined reference to `strlcpy'
getpath.c:(.text+0x97): undefined reference to `strlcpy'
getpath.c:(.text+0x153): undefined reference to `strlcat'
getpath.c:(.text+0x1b3): undefined reference to `strlcpy'
getpath.c:(.text+0x262): undefined reference to `strlcat'
../common/librtrad.a(gethomedir.c.o): In function `gethomedir':
gethomedir.c:(.text+0x4f): undefined reference to `strlcpy'
gethomedir.c:(.text+0x99): undefined reference to `strlcpy'
gethomedir.c:(.text+0xda): undefined reference to `strlcpy'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/icalc] Error 1
make[1]: *** [src/cal/CMakeFiles/icalc.dir/all] Error 2
make: *** [all] Error 2

**Comment by nljones** [comment]
This appears to be a problem with locating some core c files, not related to Accelerad. Accelerad has not been tested on CentOS.

**Comment by kusozayka** [comment]
Al right. Thanks for the fast reply! I'll do some more research regarding this issue.
